/* 
  Sketch generated by the Arduino IoT Cloud Thing "aec"
  https://create.arduino.cc/cloud/things/1471da84-1e7d-4a91-990f-d88eef02a686 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch back;
  CloudSwitch forward;
  CloudSwitch left;
  CloudSwitch right;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  pinMode(D1,OUTPUT);
  pinMode(D2,OUTPUT);
  pinMode(D3,OUTPUT);
  pinMode(D4,OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since Forward is READ_WRITE variable, onForwardChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onForwardChange()  {
  if(forward){
    digitalWrite(D1,HIGH);
  }
  else{
    digitalWrite(D1,LOW);
  }
  // Add your code here to act upon Forward change
}

/*
  Since Back is READ_WRITE variable, onBackChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBackChange()  {
   if(back){
    digitalWrite(D2,HIGH);
  }
  else{
    digitalWrite(D2,LOW);
  }
  // Add your code here to act upon Back change
}

/*
  Since Left is READ_WRITE variable, onLeftChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLeftChange()  {
  
   if(left){
    digitalWrite(D3,HIGH);
  }
  else{
    digitalWrite(D3,LOW);
  }
  // Add your code here to act upon Left change
}
/*
  Since Right is READ_WRITE variable, onRightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRightChange()  {
   if(right){
    digitalWrite(D4,HIGH);
  }
  else{
    digitalWrite(D4,LOW);
  }
  // Add your code here to act upon Right change
}